#!/bin/bash

# Generates the nativeBuild.properties file.
# Each build number is the unix timestamp of the most recent git commit
# touching the relevant native source directories.

getLatestTimestamp(){
	git log -1 --format="%ct" -- "$@"
}

propertyFile="nativeBuild.properties"
echo propertyFile=$propertyFile

echo "# DO NOT EDIT THIS FILE - it is generated by updateNativeBuildProperties.sh" > $propertyFile
echo jpen.provider.xinput.nativeBuild=$(getLatestTimestamp "src/main/c/linux" "src/main/c/utils") >> $propertyFile
echo jpen.provider.wintab.nativeBuild=$(getLatestTimestamp "src/main/c/windows" "src/main/c/utils") >> $propertyFile
echo jpen.provider.osx.nativeBuild=$(getLatestTimestamp "src/main/c/osx") >> $propertyFile
